version: '3.9'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
#  db:
#    image: postgres:15
#    environment:
#      - "POSTGRES_HOST_AUTH_METHOD=trust"

#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: demo-pgadmin #you can change this
#    depends_on:
#      - db
#    ports:
#      - "5432"
#    environment:
#      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
#      PGADMIN_DEFAULT_PASSWORD: root
#    restart: always
