# Generated by Django 4.2.2 on 2023-06-09 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='genus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bird.genus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='phylum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bird.phylum'),
        ),
        migrations.AlterField(
            model_name='family',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bird.order'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bird.family'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bird.class'),
        ),
    ]
