# Generated by Django 4.2.2 on 2023-06-11 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0002_species_genus_alter_class_phylum_alter_family_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='animal',
        ),
        migrations.AddField(
            model_name='animal',
            name='species',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bird.species'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='name',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
    ]
