# Generated by Django 4.2.2 on 2023-06-11 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0003_remove_species_animal_animal_species_species_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='species',
        ),
        migrations.RemoveField(
            model_name='species',
            name='id',
        ),
        migrations.RemoveField(
            model_name='species',
            name='name',
        ),
        migrations.AddField(
            model_name='species',
            name='animal',
            field=models.OneToOneField(default=11, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bird.animal'),
            preserve_default=False,
        ),
    ]
